version: "3"

services:
    app:
        build: ./app
        container_name: app
        depends_on:
            - mysql
        volumes:
            - ./app.log:/app/app.log

    mysql:
        image: mysql:latest
        env_file: 
            - ./.env
        volumes: 
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./my.cnf:/etc/mysql/my.cnf

    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app
        ports:
            - "80:80"
    st-agent:
        image: sematext/agent:latest
        privileged: true
        environment:
            - INFRA_TOKEN=87437305-b347-4580-9be9-41cbbbb42a70
            - SERVER_BASE_URL=https://spm-receiver.sematext.com
            - LOGS_RECEIVER_URL=https://logsene-receiver.sematext.com
            - EVENT_RECEIVER_URL=https://event-receiver.sematext.com
            - COMMAND_SERVER_URL=https://command.sematext.com
        cap_add:
            - SYS_ADMIN
        restart: always
        volumes:
            - /:/hostfs:ro
            - /etc/passwd:/etc/passwd:ro
            - /etc/group:/etc/group:ro
            - /var/run/:/var/run
            - /sys/kernel/debug:/sys/kernel/debug
            - /sys:/host/sys:ro
            - /dev:/hostfs/dev:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro